version: '3.8'
services:
  app:
    build:
      context: web
      dockerfile: app.Dockerfile
    container_name: php
    working_dir: /var/www
    volumes:
      - ./web:/var/www
    networks:
      - app-network
  database:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    env_file:
      - ./.env
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./web:/var/www
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
