<div class="container pt-4">
    <div class="d-flex align-items-center justify-content-center">
        <form action="/upload" class="border p-3" method="post" enctype="multipart/form-data">
            <div class="input-group mb-6">
                <p>Upload a CSV file</p>
            </div>
            <div class="input-group mb-3">
                <input type="file" class="form-control" placeholder="File" name="file">
            </div>
            <div class="input-group mb-2">
                <input class="btn btn-primary" type="submit">
            </div>
        </form>
    </div>
</div>

