<div class="container pt-4">
    <div class="d-flex align-items-center justify-content-center">
        <form action="/auth" class="border p-3" method="post">
            <div class="input-group mb-6">
                <p>Log In</p>
            </div>
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Username" name="username">
            </div>
            <div class="input-group mb-3">
                <input type="password" class="form-control" placeholder="Password" name="password">
            </div>
            <div class="input-group mb-2">
                <input class="btn btn-primary" type="submit">
            </div>
        </form>
    </div>
</div>

